# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='files')),
                ('return_csv', models.TextField()),
            ],
        ),
    ]
